### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by Opalo** [alexpanov/freeportfinder#6]
Hi,

I see that the project is failing on CI, because of unsupported JDKs being set up. For [xenial](https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support) the following are supported:
```
Pre-installed JVMs: openjdk8, openjdk10, and openjdk11 on x86, default is openjdk8; openjdk7 and openjdk8 on ppc64le.
```

Would you like me to prepare a PR? What are your requirements?

**Comment by alexpanov** [comment]
Hi @Opalo. Thank you for submitting the issue. I have just bumped the JDK versions and the build seems to be running fine now.
